### ISSUE TITLE
Cannot screenshot multiple stories with addDecorator

### ISSUE THREAD

**Issue by camsloanftc** [tsuyoshiwada/storybook-chrome-screenshot#10] opened 2017-10-05 04:35 UTC
First of all, need to say this is a great add-on. Thanks!

**Issue:**
When looping over stories, addDecorator seems to get stuck after a single story. It will only generate the images for the one story.

As mentioned by @gcazaciuc in #3, it would be very handy not to have to decorate every story manually.

**This does not work:**
```javascript
storiesOf('corp-site/atoms/Button', module)
  .addDecorator(withScreenshot(getScreenshotOptions))
  .add('with Black and Active', () => (
    <Button color="black" isActive>Button</Button>
  ))
  .add('with White and inactive, also inaccessible', () => (
    <Button color="white">Button</Button>
  ))
  .add('with Purple and inactive', () => (
    <Button color="purple">Button</Button>
  ))
```

It will only take screenshots of the first story: `with Black and Active`.

It would be great to be able to use the `addDecorator` globally within the config to take screenshots of all stories that are being imported and looped over.

**Comment by alexeybondarenko** [comment] 2017-10-16 13:18
Have the same issue

**Comment by alexeybondarenko** [comment] 2017-10-16 22:50
This change to the example breaks down creating screenshots.

https://github.com/tsuyoshiwada/storybook-chrome-screenshot/compare/master...alexeybondarenko:master

**Comment by tsuyoshiwada** [comment] 2017-10-17 12:48
Hi @camsloanftc Thank you for issues! and sorry late...

Is it possible to tell me which version the problem will occur?
Also, if you encounter any errors when using the `--debug` option, it will be helpful if you let me know together :pray:

**Comment by alexeybondarenko** [comment] 2017-10-17 13:13
I've debugged what in my case, withScreenshot for the story Button.withText is called twice. Therefore counter is more than the results.lengts. 
Can't understand why

**Comment by tsuyoshiwada** [comment] 2017-10-17 13:13
Hi @alexeybondarenko Thank you for report!
It's a big help :+1:

**Comment by tsuyoshiwada** [comment] 2017-10-17 13:23
@alexeybondarenko I could confirm that `with text` was called twice in the same way. I would like to take a closer look.

**Comment by tsuyoshiwada** [comment] 2017-10-17 15:57
@camsloanftc @alexeybondarenko 
Released as `0.6.1`. Please check when you have time.

**Comment by alexeybondarenko** [comment] 2017-10-17 17:02
@tsuyoshiwada thanks 👍  In `0.6.1` the bug with the freezing was fixed.

But I've found the new one. It's related to https://github.com/tsuyoshiwada/storybook-chrome-screenshot/issues/3. 
I've added the global decorator and in the result, not all stories were screenshotted.

https://github.com/alexeybondarenko/storybook-chrome-screenshot/commit/5160effbb0ebfadae9e4b92394677fa5026b5563

Didn't were created the screenshots for:
Tag.with text
Tag.with large size
Heading.with subtitle

**Comment by alexeybondarenko** [comment] 2017-10-17 17:20
This could help to debug
https://github.com/alexeybondarenko/storybook-chrome-screenshot/commit/3617b2c261aed5b4e95d6d882437e86042873ed1


Log: [debug.log](https://github.com/tsuyoshiwada/storybook-chrome-screenshot/files/1391961/debug.log)

**Comment by tsuyoshiwada** [comment] 2017-10-24 05:34
Hi @alexeybondarenko Thank you for confirmation :smiley:

There seems to be a case that screenshots are not taken when using the global decorator as you say.
It may take some time to fix the bug. It will be very helpful if you can PR if possible :+1:

**Comment by alexeybondarenko** [comment] 2017-10-24 08:06
@tsuyoshiwada okay 😀 I will try to fix it

**Comment by alexeybondarenko** [comment] 2017-12-05 12:55
Hi @tsuyoshiwada, @camsloanftc. I've made the PR, that is fixing a lot of the race conditions in the capturing process. I'm using my fork in the project, that has 120+ stories (syftapp.com). All these stories are capturing by this plugin and are uploading to Argos Ci for the visual regression testing.
I would be appreciated for the review. 😄

**Comment by tsuyoshiwada** [comment] 2017-12-09 17:05
Hi @alexeybondarenko @camsloanftc I merged #14 PR. Released it as `v0.8.0` :tada:
Please check when you have time :)

**Comment by alexeybondarenko** [comment] 2018-01-08 15:09
@tsuyoshiwada 👍 it works. I think we can close it.

**Comment by tsuyoshiwada** [comment] 2018-01-08 15:14
@alexeybondarenko Thanks :smiley: !  Close this Issue.

**Closed by tsuyoshiwada** 2018-01-08 15:14 UTC

**Comment by camsloanftc** [comment] 2018-01-08 16:45
Can confirm this works in 0.8.0 as well. Thanks!

**Comment by theKashey** [comment] 2018-04-25 14:36
1.1.0-alpha.1 – a lot of screenshots are duplicated. I could see button for button story, checkbox, and even App story. It does not got updated.
Using withScreenshot as a global decorator.
